parser: babel-eslint
parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: true
extends: airbnb
plugins: 
  - react
  - jsx-a11y
  - import
  - react-native
env:
  es6: true
  browser: true
  node: true
globals: 
  __IOS__: true
  __ANDROID__: false
  __DEV__: true
settings:
  import/resolver: 
    babel-module:
      root:
        - "./src"
rules: 
  react/jsx-filename-extension: off
  react/prefer-stateless-function: warn
  react/prop-types: off
  dot-notation: warn




