source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/rogerabyss/myrepo.git'

platform :ios, '9.0'
use_frameworks!

target 'abyss' do
    # skeleton UI
    pod "SkeletonView", "~> 1.0.4"
    
    # Fabric & Crashlytics
    pod 'Fabric'
    pod 'Crashlytics'

    # React 
    # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
        'Core',
        'CxxBridge',  # Include this for RN >= 0.47
        'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
        'RCTNetwork',
        'RCTText',
#        'RCTImage',
        'RCTWebSocket', # needed for debugging
        # Add any other subspecs you want to use in your project
    ]

    # Explicitly include Yoga if you are using RN >= 0.42.0
    # 跨平台布局
    pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

    # Third party deps podspec link
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end
